### ISSUE TITLE
Create component: Card.tsx 

### ISSUE THREAD

**Issue by artyomkorshykau** [VeryStone69/project_cards#34]

**Comment by exleonardo** [comment]
### (cards preview) click to deck url
![Image](https://github.com/VeryStone69/project_cards/assets/64332326/b719ec72-5a98-433e-a106-552f81e3d43e)
### open my card

![Image](https://github.com/VeryStone69/project_cards/assets/64332326/256cfff3-baba-45fa-bf02-3b7b40cdd1c3)
