### ISSUE TITLE
Create API : Create authApi.ts in services folder. Config this API: (create endpoint) and add export hooks.Click and check

### ISSUE THREAD

**Issue by exleonardo** [VeryStone69/project_cards#41]

**Comment by exleonardo** [comment]
### check

![Image](https://github.com/VeryStone69/project_cards/assets/64332326/f62deca2-beb2-42b9-a027-3c3dbf481b89)

### example
![Image](https://github.com/VeryStone69/project_cards/assets/64332326/943f368a-1df5-48ca-821d-3091d8dd1e30)


### final api
![Image](https://github.com/VeryStone69/project_cards/assets/64332326/ff5f49a8-32a3-46a7-90ed-8c4a802a85d9)

**Comment by artyomkorshykau** [comment]
[![Typing SVG](https://readme-typing-svg.herokuapp.com?font=Fira+Code&weight=600&size=40&pause=1000&color=6EF742&random=false&width=435&height=60&lines=%D0%97%D0%90%D0%95%D0%91%D0%A3%D0%9C%D0%91%D0%90!)](https://git.io/typing-svg)
