### ISSUE TITLE
Create Component : FileUploader.tsx : Click and Check Photo

### ISSUE THREAD

**Issue by exleonardo** [VeryStone69/project_cards#44]
![Image](https://github.com/VeryStone69/project_cards/assets/64332326/f3ed268f-0ca1-45b8-a6be-5e57ed65705f)

**Comment by artyomkorshykau** [comment]
[![Typing SVG](https://readme-typing-svg.herokuapp.com?font=Fira+Code&pause=1000&random=false&width=435&lines=%D0%9D%D0%95+%D0%90%D0%A5%D0%A3%D0%95%D0%9D%D0%9D%D0%9E)](https://git.io/typing-svg)
