### ISSUE TITLE
Create component: ( CardForm.tsx) Click check Photo

### ISSUE THREAD

**Issue by exleonardo** [VeryStone69/project_cards#45]
### final version
![Image](https://github.com/VeryStone69/project_cards/assets/64332326/f707ead0-86cb-4949-ac31-09ca4a710d38)

### choice select text
![Image](https://github.com/VeryStone69/project_cards/assets/64332326/f85bffb1-298c-41ef-926e-1b2a4e33d9b7)

### Choice Picture
![Image](https://github.com/VeryStone69/project_cards/assets/64332326/387d4b9c-d823-4c04-8e80-0e399765c37c)

**Comment by artyomkorshykau** [comment]
[![Typing SVG](https://readme-typing-svg.herokuapp.com?font=Fira+Code&pause=1000&random=false&width=435&lines=%D0%90%D0%A5%D0%A3%D0%95%D0%9D%D0%9D%D0%9E)](https://git.io/typing-svg)
